### ISSUE TITLE
Re-consider use of `export default` syntax

### ISSUE THREAD

**Issue by coodoo** [taiansu/generator-rf#11]
As stated [here](http://stackoverflow.com/questions/21117160/what-is-export-default-in-javascript), seems `export default` is no longer current, might be safer to fall back on good old `module.exports`?

**Comment by taiansu** [comment]
Thanks for remind, will fix it later.

**Comment by taiansu** [comment]
Yesterday I found that the `export default` thing is in the final draft of [April 14, 2015 Rev 38 Final Draft](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts) section 15.2.3. I'll put them back in the coming version if no objections.

**Comment by coodoo** [comment]
makes sense!
