### ISSUE TITLE
Cannot find module 'coffee-react-transform' in npm test

### ISSUE THREAD

**Issue by tomin** [taiansu/generator-rf#7]
Scenario:
» npm test

> ls@0.0.0 test /...
> jest

Using Jest CLI v0.2.2
 FAIL  src/scripts/components/__tests__/App-test.ls
Error:  ../preprocessor.js: Cannot find module 'coffee-react-transform'
1 test failed, 0 tests passed (1 total)
Run time: 0.318s
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

My fix:
in package.json, in devDependencies section, add 
+    "coffee-react-transform": "*"

run npm install again

**Comment by taiansu** [comment]
@tomin Hi, thanks for bug report. I can reproduce the issue and will fix it asap.

**Comment by taiansu** [comment]
Fixed in [0.1.18](https://github.com/taiansu/generator-rf/commit/f0ab1f4fc46527e3fd59026b6e433dfd62933918).
