### ISSUE TITLE
`npm test` gives segmentation falut

### ISSUE THREAD

**Issue by taiansu** [taiansu/generator-rf#8]
When running `npm test` in generate coffee-script or livescript project, it always crashes with `segmentation fault` in environment:

> node v0.12.0
npm 2.6.0
jest 0.4.0

When downgrade to
> node v0.11.16
npm 2.6.0
jest 0.3.0

will have different error which solved in jest 0.4.0

"Please run node with the --harmony flag!"
https://github.com/facebook/jest/issues/244

**Comment by taiansu** [comment]
Seems jest don't work well with node v0.12.0. https://github.com/facebook/jest/issues/243

**Comment by taiansu** [comment]
According the mentioned link, this issue won't be fix soon because JSDOM dropping node support. So just use either node v0.10.3x or iojs will solve the issue for now.

**Comment by transedward** [comment]
thanks so support, what is the version of iojs that can solve the problem?

**Comment by taiansu** [comment]
@transedward I tried serval and found jest works on v1.6.3 and above.

**Comment by transedward** [comment]
@taiansu thanks
